#:schema node_modules/wrangler/config-schema.json
name = "janwilmake_schedule-each"
main = "worker.ts"
compatibility_date = "2024-12-27"
assets = { directory = "./public" }
routes = [
  # when hosting this yourself, remove this or exchange it for a domain you use at cloudflare
  { pattern = "schedule-each.actionschema.com", custom_domain = true }
]

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RequestSchedulerDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RequestSchedulerDO"]